### ISSUE TITLE
Count filtered collection

### ISSUE THREAD

**Issue by AlexParamonov** [recurly/recurly-client-ruby#181]
```
Recurly::Account.where(account_code: "foobar").count
```
Returns total account count.
It is not a gem bug, but API.

Please remove method or implement API response for this case.

**Comment by AlexParamonov** [comment]
For anyone curious, the 
```
Recurly::Account.where(uri: Recurly::Account.member_path(user.email)).count
```
sends the current request

**Comment by chrissrogers** [comment]
Since the account list endpoint only supports indexing by an account's `state` property, that is the only property by which you will be able to scope your `Recurly::Account` index request.

For example:

```ruby
Recurly::Account.where(state: :active).count
```

In the case you illustrate above, the best way to get the account would be to use something like the following:

```ruby
Recurly::Account.find('foobar')
```

[See account documentation for more detail](https://docs.recurly.com/api/accounts#list-accounts).

**Comment by bhelx** [comment]
@AlexParamonov Please re-open if you aren't satisfied with chris' answer and we can talk about some kind of implementation to solve your problem

**Comment by AlexParamonov** [comment]
I use the one posted above:
```
Recurly::API.head Recurly::Account.member_path("foobar")
```
it does what I need, thanks.
