### ISSUE TITLE
resource valid but with errors

### ISSUE THREAD

**Issue by gagalago** [recurly/recurly-client-ruby#285]
When I redeem a coupon, sometime I have errors but the coupon is valid?
```ruby
coupon = Recurly::Coupon.find("my-coupon")
coupon.redeem(account)
coupon.valid? # true
coupon.errors # {"base"=>["has reached max redemptions for this account"]}
```
How can I modify `resource.rb` to be able to easily know that there is some errors.
I think that the best way is to add a method `errors?` in place of changing the behaviour of `valid?`

What do you  think?

**Comment by bhelx** [comment]
@gagalago This is some semantic weirdness with the API and is happening because the error is put on the `Coupon` here for some reason. The coupon itself is valid, it's the redemption that is not valid. If you want to use `redeem` rather than `redeem!`, it might make more sense in your code to check the returned `Redemption`:

```ruby
redemption = coupon.redeem(account)
redemption.errors # {"base"=>["has reached max redemptions for this account"]}
```

> How can I modify resource.rb to be able to easily know that there is some errors.
> I think that the best way is to add a method errors? in place of changing the behaviour of valid?

We typically use the `.any?` method on the errors object for this. `.errors` is of type `Resource::Errors` which inherits from `Hash`. https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/errors.rb#L3

```ruby
redemption = coupon.redeem(account)
if redemption.errors.any?
  # alert your user with a message 
else
  # the redemption was successful
end
```

Also keep in mind that you can apply coupon codes at the time of creating charges or subscriptions by setting the coupon code on those objects respectively.

Let me know if that answers your questions.

**Comment by bhelx** [comment]
Feel free to reopen if you don't think I answered the question.
