### ISSUE TITLE
Inconsistent pagination behavior for invoices

### ISSUE THREAD

**Issue by schneidmaster** [recurly/recurly-client-ruby#350]
I have noticed some strange and inconsistent behavior for invoice pagination. This may be generally applicable to pagination for records using `has_many` in your gem codebase, but I only really dug into it for invoices since that's what I was working with.

Take a Recurly account with 75 invoices (so more than one API page, since 50 can be returned per page by default)

```ruby
account = Recurly::Account.find(some_id)

account.invoices.collect(&:invoice_number).count
# => 50
# i.e. `collect` does not auto-paginate the API

account.invoices.find_each.map(&:invoice_number).count
# => 75
# i.e. `find_each` does auto-paginate the API

account.invoices.find_each.map(&:invoice_number).count
# => 25
# calling `find_each` a second time only provides the last page of records?

account.invoices.collect(&:invoice_number).count
# => 25
# calling `collect` again after `find_each` also only provides the last page of records?
```

Replacing `collect` with `map` above gives the same result. So there are potentially two problems at play:

1. There seems to be a bug in which only the last page of API responses from `find_each` is cached and then you can't get the full list of invoices again without instantiating a new record.
2. I think `find_each` and `collect`/`map` should have consistent behavior with regards to auto-pagination, and/or that the difference should at least be better documented. It's less obvious that this is a bug, but it's an inconsistent behavior, and it's unexpected since a lot of Recurly's ruby API mirrors ActiveRecord which obviously doesn't have that distinction.

**Comment by bhelx** [comment]
@schneidmaster I agree 100% with your overall point that the pagination code is not very clear and has lots of inconsistent behavior. I'm working on PR #334 to fix some of these problems and I'm hoping to get all the changes into that one PR (since they will be breaking changes).

There is a lot of hackery in the Pager class in order to present an Enumerable like interface:
https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/pager.rb#L243-L253
https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/pager.rb#L24
https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/pager.rb#L99

Not only is this code unclear and not working, it's not maintainable. 

What I'd like to do is remove all of this stuff and only support 2 interfaces. `find_each(opts: Hash)` and `paginate`. If there are any changes or ideas you want to get in, let's discuss them in #334. Happy to discuss putting in whatever you need.

**Comment by schneidmaster** [comment]
@bhelx Makes sense, thanks. I'm not strongly opinionated about how it ought to work -- I think simplifying the API to avoid inconsistent method behaviors would be sufficient in itself.

**Comment by aaron-suarez** [comment]
The PR for #334 turned out to be a dud. Closing this out as it is not actionable in this major version of the library
