### ISSUE TITLE
Noisy Output when Using gem with Rails

### ISSUE THREAD

**Issue by ChaoticBoredom** [recurly/recurly-client-ruby#385]
The latest set of security patches have introduced some very noisy warnings with regards to logging.
```
[WARNING] Recurly logger has been disabled. If you wish to use it,
only do so in a non-production environment and make sure
the `RECURLY_INSECURE_DEBUG` environment variable is set to `true`.
```
While helpful at times, this contributes to a large amount of noise, and this message cannot be disabled or hidden.
Additionally, setting `RECURLY_INSECURE_DEBUG` will instead output a different, but equally verbose message.
Setting this message on enabling the insecure option makes sense, having it displayed on the default secure setting doesn't and adds to general logging noise while not providing value.

Is it possible that this could be changed?

**Comment by bhelx** [comment]
@ChaoticBoredom sorry for the annoyance. Because it represents a security concern, we want it to be fairly annoying if enabled in production. In your case, the Railtie was automatically setting the logger: https://github.com/recurly/recurly-client-ruby/commit/b4b5b4b60e1e38238917b0b053678f4a6e78b2e0

I've fixed this for rails users and it will go out in the next release.

**Comment by ChaoticBoredom** [comment]
Thanks @bhelx . I definitely get having the warning, esp if the insecure value is set, but it was frustrating to not be able to disable it when the insecure value wasn't set and we weren't intentionally trying to log anything.

**Comment by bhelx** [comment]
Yeah I get it, really sorry about that. I missed the railtie in the security update.
