### ISSUE TITLE
Invalid subscription add_on leads to unhandled exceptions

### ISSUE THREAD

**Issue by Sinetheta** [recurly/recurly-client-ruby#400]
When making a `Recurly::Purchase.invoice!(purchase)` with a purchase that includes a subscription with invalid add_ons (eg: non-existent add_on_code) the following unhandled exception occurs

```ruby
NoMethodError: undefined method `invalid!' for #<Recurly::Subscription::AddOns:0x00007f89ffe88510>
```

I think this is because the recursive `invalid!` error handling expects everything along the way to be a `Resource` but `Recurly::Subscription::AddOns` are not.

A cursory examination of the API response suggests the solution may be non trivial

```xml
<error field="purchase.subscriptions[0].subscription_add_ons.add_on" symbol="">is invalid</error>
```

I would have expected the API to specify _which_ was the offending subscription_add_on

**Comment by bhelx** [comment]
@Sinetheta at first glance, this appears to be an issue with the way the API is rendering that xml field:

`purchase.subscriptions[0].subscription_add_ons.add_on` should be something like this: `purchase.subscriptions[0].subscription_add_ons[0].add_on`.

We will take a look at it.

**Comment by Sinetheta** [comment]
Thanks, but I think there are two problems. The API response could use an index and it would be nice if it returned _all_ of the mistakes instead of just the first invalid add-on it encounters.

But even if it were to do so, I don't think the gem would parse it in it's current state. That's why I came here instead of just reporting to `support@recurly.com` my temporary workaround is

```
module Recurly
  class Subscription
    # This class does not inherit from Resource like almost everything else
    # in the recurly gem. As such it's missing a place to hang subscription
    # addons errors.
    # https://github.com/recurly/recurly-client-ruby/issues/400
    AddOns.class_eval do
      def errors
        @errors ||= Resource::Errors.new { |h, k| h[k] = [] }
      end

      def invalid!(attribute_path, error)
        errors[attribute_path[0]] << error
      end
    end
  end
end
```

Don't judge me 😉

**Comment by dixalex** [comment]
+1 

@bhelx Not pushing, but any update on this?

**Comment by yoavfranco** [comment]
@bhelx Hi! we're also seeing a similar issue but with `coupon_code` in the `Recurly::Purchase.invoice!(purchase)`. I suspect that it stems from the same source.
 We're getting `NoMethodError: undefined method `invalid!' for "[COUPON_CODE]":String`

It's been a month since this was last updated, sorry to be pushy, but is there an expected fix anytime soon?

Thanks in advance

**Comment by JohnBDonner** [comment]
This same thing is happening to me with the `Recurly::Plan` object.

I try to update a `Plan` with new pricing info:

```ruby
plan.unit_amount_in_cents['BRL'] = 329_00
plan.save
```

And this raises an unhandled exception:
```ruby
*** NoMethodError Exception: undefined method `invalid!' for #<Recurly::Money:0x00007fbabd9e1b58>
```

After some digging, I noticed that I'm getting a `422` error, with an error response body:
```
<error field='plan.unit_amount_in_cents.BRL' symbol='inclusion'>is not accepted by the site</error>
<error field='plan.setup_fee_in_cents.BRL' symbol='inclusion'>is not accepted by the site</error>
```

Two things are odd to me here:
1. the message of this `422` error never gets to me, because the `Money` class doesn't implement `#invalid!`
2. `BRL` seems to be supported [according to the Recurly docs](https://docs.recurly.com/docs/currencies#section-supported-currencies), yet it seems that Recurly doesn't want to accept it?

**Comment by drewish** [comment]
@JohnBDonner did you enable that currency on the site on `/configuration/currencies`?

**Comment by JohnBDonner** [comment]
@drewish Yes, I actually ended up enabling `BRL` 👍 I had forgotten that was necessary 😅 

Though, the `undefined method 'invalid!'` error should still be fixed. I think `#invalid!` needs to either be included on the subresources (which don't currently inherit from `Resource`) or it needs to handle non-`Resource` objects as attributes.

**Comment by aaron-suarez** [comment]
@yoavfranco, Can you please provide a code sample? I did the following without encountering a NoMethodError:

```ruby
require 'securerandom'

purchase = Recurly::Purchase.new({
  currency: 'USD',
  collection_method: :automatic,
  po_number: '98675',
  account: {
    account_code: SecureRandom.uuid,
    billing_info: {
      first_name: 'Aaron',
      last_name: 'Du Monde',
      address1: '400 Alabama St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94110',
      country: 'US',
      number: '4111-1111-1111-1111',
      month: 12,
      year: 2019,
    },
  },
  subscriptions: [
    {
      plan_code: "gold"
    }
  ],
  coupon_codes: [
    "COUPON123" # Not a valid coupon code on my site
  ]
})

begin
  collection = Recurly::Purchase.invoice!(purchase)
  puts collection.inspect
rescue Recurly::Resource::Invalid => e
  puts e.inspect # printed #<Recurly::Resource::Invalid: coupon_codes[0] Coupon code COUPON123 is invalid>
end
```

**Comment by aaron-suarez** [comment]
@Sinetheta @dixalex @yoavfranco @JohnBDonner The fix from #455 was released just now to rubygems

**Comment by JohnBDonner** [comment]
@aaron-suarez Thanks! 

Is it possible to see the detailed error message of these nested resources after this fix?

For example, this XML response:

```xml
<error field="plan.unit_amount_in_cents.BRL" symbol="inclusion">is not accepted by the site</error>
```

Being shown instead of just:

```ruby
plan.errors
# => {"unit_amount_in_cents"=>["is invalid"]}
recurly_plan.errors.full_messages
# => ["Unit amount in cents is invalid."]
```
?

**Comment by aaron-suarez** [comment]
No, I don't think so. Here's the particular code that handles these errors:
```ruby
    def invalid!(attribute_path, error)
      if attribute_path.length == 1
        errors[attribute_path[0]] << error
      else
        child, k, v = attribute_path.shift.scan(/[^\[\]=]+/)
        if c = k ? self[child].find { |d| d[k] == v } : self[child]
          c.invalid! attribute_path, error if c.methods.include? :invalid!
          e = errors[child] << 'is invalid' and e.uniq!
        end
      end
    end
```
In the scenario we're talking about, it gets down to the line `c.invalid! attribute_path, error if c.methods.include? :invalid!`

If `c` were a `Resource`, the `invalid!` method would put the `error` (which is the error message, "is not accepted by the site" in this case) in the errors hash of the sub-object. But because `c` is not a `Resource` in this case, the `error` doesn't really get stored anywhere, it just kind of drops off.

If you'd like to do a PR to store that somewhere that makes sense for non-Resources, I would be happy to review it. If you don't have the bandwidth for that, feel free to open another issue and we'll fix it in a future release.

Otherwise, I think your workaround should be fine, although rather annoying I'm sure.
