### ISSUE TITLE
Cannot create account acquisition using `build_account_acquisition`

### ISSUE THREAD

**Issue by renatolond** [recurly/recurly-client-ruby#487]
**Describe the bug**

When we try to create a new account acquisiton, we get a 404.

**To Reproduce**

Using an existing account, do:

```
          account.build_account_acquisition
          account.account_acquisition.channel = acquisition_params[:channel]
          account.account_acquisition.subchannel = acquisition_params[:subchannel]
          account.account_acquisition.campaign = acquisition_params[:campaign]
          account.account_acquisition.save!
```

**Expected behavior**

During the save we get:
```
Recurly::API::NotFound: 404 Not Found (POST https://api.recurly.com/v2/accounts/XXXXXX/account_acquisition)
```
It seems to me it should be posting to /acquisition, is it the wrong way to build an account acquisition?

**Your Environment**

- Which version of this library are you using? 2.17.11
- Which version of ruby are you using? 2.5.3

**Comment by drewish** [comment]
Does `account` already exist or is it a new object too?

**Comment by renatolond** [comment]
It usually is new, created with:
```
account = Recurly::Account.create!(
account_code: account_code,
...
)
```

followed by updating billing info (which is partially passed during account creation), something like:

```
account.billing_info.state = state
...
account.billing_info.save!
```

And then we start to fill account_acquisition.

**Comment by aaron-suarez** [comment]
@renatolond You are correct, it should be posting to `/acquisition` but the library is currently attempting to post to `/account_acquistion` which is incorrect. We'll work out a fix for it, thanks for reporting this!

**Comment by aaron-suarez** [comment]
@renatolond After looking at the problem further, I realize that fixing the posting destination wouldn't actually fix the problem, because calling `account.build_account_acquisition` in this manner would post it without the body. We will consider figuring out a way to either support or remove this interface because you are correct that it does not work. In the meantime, I suggest using the following code for your integration:

```ruby
          account.account_acquisition = {
            channel: acquisition_params[:channel],
            subchannel:  acquisition_params[:subchannel],
            campaign: acquisition_params[:campaign]
          }

          account.save!
```

**Comment by aaron-suarez** [comment]
I have just updated the documentation for the examples for Account Acquisition. Please see https://dev.recurly.com/docs/create-account-acquisition for examples.

**Comment by aaron-suarez** [comment]
@renatolond I wanted to drop another note to make sure that you're aware that you don't have to make so many calls to the API as you appear to be making. It would work just fine if you initialize an account object, then add the acquisition info as well as the billing info, then call `account.save!` which will save all of the information in one API call. Without knowing more details of your integration, it's difficult to say whether this many API calls is intentional and necessary, but if it's not, you might find that calling it all in one `save` call should make things a bit more performant.
