### ISSUE TITLE
Unable to perform 3DS with Create Subscription as per docs

### ISSUE THREAD

**Issue by scsmith** [recurly/recurly-client-ruby#737]
I'm trying to implement 3DS. Whilst most of it has been working for a while we're now seeing a few new failures on create subscription.

Looking at the 3DS2 documentation (Step 6) https://developers.recurly.com/guides/3ds2.html#step-6-submit-new-purchase-request. It states:

"The three_d_secure_action_result_token_id is a valid parameter on the Create Billing Info endpoint and on any Recurly API endpoint that accepts a Billing Info, including Create Purchase, Create Subscription, Update Subscription, Create Account, Collect Invoice, Create Gift Card."

However, whilst it is on the upgrade endpoint it doesn't seem to be on the create subscription endpoint here: https://developers.recurly.com/api/v2021-02-25/index.html#operation/create_subscription or in this code?

However, the create action does raise the TransactionError that forces you to generate the `three_d_secure_action_result_token_id`.

How can we handle the requirement for 3DS in order to create a subscription?

**Comment by tilley-kyle** [comment]
Hi @scsmith 
If I am understanding your request/question correctly, you are asking about sending in the `three_d_secure_action_result_token_id` param into a create_subscription request because it isn't there?

If that is correct, then I can point out where the `three_d_secure_action_result_token_id` lives in that endpoint so you can handle that requirement. In this case looking at the [create subscription endpoint](https://developers.recurly.com/api/v2021-02-25/index.html#operation/create_subscription) the `three_d_secure_action_result_token_id` is nested in create_subscription -> account -> billing_info.

In general `three_d_secure_action_result_token_id` will live inside billing_info which in turn lives in account. There are some exceptions such as in collect_invoice, where it exists at the top level. 

I hope this answers your question on how to input that field to satisfy the 3ds2 requirement, if not please follow up in here!

**Comment by scsmith** [comment]
Thanks, that resolved this. However, is there a reason why the create subscription change endpoint does not raise the 422 error and instead just returns a success and then goes into the dunning process?

**Comment by tilley-kyle** [comment]
Great! 
Can I get repro steps on what exactly you're doing as well as the id/uuid of the subscriptions you are attempting to make the change on? I was able to 'properly' go through the 3ds flow here and I'll need some more info on what is going wrong so we can solve this for you!

**Comment by tilley-kyle** [comment]
I'm closing this one out since it's going stale. If you have any follow up you can reopen this or create a new issue.
Thank you!
